version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    networks:
    - dmz
    environment:
      MYSQL_ROOT_PASSWORD: dbtest
      MYSQL_DATABASE: phpginfo
      MYSQL_USER: phpginfo
      MYSQL_PASSWORD: phpginfo

  site:
    build: php-apache
    volumes:
    - site_data:/var/www
    expose:
    - 80
    restart: always
    networks:
    - dmz
    - proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_HOST: db:3306
      DB_USER: phpginfo
      DB_PASSWORD: phpginfo
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${EMAIL_FOR_CERTIFICATION}
      TRUSTED_PROXIES: reverse-proxy

  save:
    build: save-strategy
    volumes:
    - site_data:/var/www
    - save_data:/var/save
    restart: always
    networks:
    - dmz
    environment:
      DB_HOST: db
      DB_USER: phpginfo
      DB_PASSWORD: phpginfo

volumes:
  db_data:
    name: db_data
  site_data:
    name: site_data
  save_data:
    name: save_data


networks:
  proxy:
    external:
      name: nginx-proxy