services:
  db:
    build: mysql
    image: mysql-phpginfo:latest
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    networks:
    - interne
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_SFTP_SQL}
      MYSQL_DATABASE: ${USER_SFTP_SQL}
      MYSQL_USER: ${USER_SFTP_SQL}
      MYSQL_PASSWORD: ${PASSWORD_SFTP_SQL}

  site:
    build: php-apache
    image: php-phpginfo:latest
    volumes:
    - site_data:/var/www
    restart: always
    depends_on:
    - db
    networks:
    - interne
    - proxy
    environment:
      VIRTUAL_HOST: ${APP_HOSTNAME}
      DB_HOST: db:3306
      DB_USER: ${USER_SFTP_SQL}
      DB_PASSWORD: ${PASSWORD_SFTP_SQL}
      NETWORK_ACCESS: ${NETWORK_RESTRICTION}
      APACHE_DOCUMENT_ROOT: ${WEB_ROOT}
      TRUSTED_PROXIES: reverse-proxy
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}

  cron:
    build: cron
    image: cron-phpginfo:latest
    volumes:
    - site_data:/site-to-save
    - save_data:/saves
    restart: always
    depends_on:
    - site
    - db
    networks:
    - interne
    environment:
      DB_HOST: db
      DB_USER: ${USER_SFTP_SQL}
      DB_PASSWORD: ${PASSWORD_SFTP_SQL}

  sftp:
    build: sftp
    image: sftp-phpginfo:latest
    restart: always
    volumes:
    - site_data:/home/${USER_SFTP_SQL}/site
    - save_data:/home/${USER_SFTP_SQL}/save
    networks:
    - sftp
    ports:
    - "22"
    command: ${USER_SFTP_SQL}:${PASSWORD_SFTP_SQL}:${UID_UTILISATEUR}:${UID_UTILISATEUR}
    environment:
      USER_SFTP: ${USER_SFTP_SQL}
      PASS_SFTP: ${PASSWORD_SFTP_SQL}

volumes:
  db_data:
    driver: local
  site_data:
    driver: local
  save_data:
    driver: local


networks:
  proxy:
    name: nginx-proxy-ginfo
    external: true
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
  sftp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
