version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    networks:
    - dmz
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: phpginfo
      MYSQL_USER: phpginfo
      MYSQL_PASSWORD: ${DB_PASSWORD}

  site:
    build: php-apache
    volumes:
    - site_data:/var/www
    restart: always
    networks:
    - dmz
    - proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_HOST: db:3306
      DB_USER: phpginfo
      DB_PASSWORD: ${DB_PASSWORD}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${EMAIL_FOR_CERTIFICATION}
      TRUSTED_PROXIES: reverse-proxy

  save:
    build: save-strategy
    volumes:
    - site_data:/site-to-save:ro
    - save_data:/saves
    restart: always
    networks:
    - dmz
    environment:
      DB_HOST: db
      DB_USER: phpginfo
      DB_PASSWORD: ${DB_PASSWORD}

  sftp:
    image: atmoz/sftp
    volumes:
    - site_data:/home/${USER_SFTP}/site
    - save_data:/home/${USER_SFTP}/save
    ports:
    - "22"
    command: ${USER_SFTP}:${PASS_SFTP}:${UID_UTILISATEUR}:${UID_UTILISATEUR}
    environment:
      USER_SFTP: USER_SFTP
      PASS_SFTP: PASS_SFTP

volumes:
  db_data:
    name: db_data
  site_data:
    name: site_data
  save_data:
    name: save_data


networks:
  proxy:
    external:
      name: nginx-proxy
  dmz:
    internal: true