version: '2'

services:
  db:
    build: mysql
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    networks:
    - interne
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_SFTP_SQL}
      MYSQL_USER: ${USER_SFTP_SQL}
      MYSQL_PASSWORD: ${PASSWORD_SFTP_SQL}

  site:
    build:
      context: php-apache
    volumes:
    - site_data:/var/www
    restart: always
    depends_on:
    - db
    networks:
    - interne
    - proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_HOST: db:3306
      DB_USER: ${USER_SFTP_SQL}
      DB_PASSWORD: ${PASSWORD_SFTP_SQL}
      NETWORK_ACCESS: ${NETWORK_ACCESS}
      APACHE_DOCUMENT_ROOT: ${WEB_ROOT}
      TRUSTED_PROXIES: reverse-proxy
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}

  cron:
    build: cron
    volumes:
    - site_data:/site-to-save:ro
    - save_data:/saves
    restart: always
    depends_on:
    - site
    - db
    networks:
    - interne
    environment:
      DB_HOST: db
      DB_USER: ${USER_SFTP_SQL}
      DB_PASSWORD: ${PASSWORD_SFTP_SQL}

  sftp:
    build: sftp
    restart: always
    volumes:
    - site_data:/home/${USER_SFTP_SQL}/site
    - save_data:/home/${USER_SFTP_SQL}/save
    networks:
    - sftp
    ports:
    - "22"
    command: ${USER_SFTP_SQL}:${PASSWORD_SFTP_SQL}:${UID_UTILISATEUR}:${UID_UTILISATEUR}
    environment:
      USER_SFTP: ${USER_SFTP_SQL}
      PASS_SFTP: ${PASSWORD_SFTP_SQL}

volumes:
  db_data:
    name: db_data
  site_data:
    name: site_data
  save_data:
    name: save_data


networks:
  proxy:
    external:
      name: nginx-proxy-ginfo
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
  sftp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'