version: '2'

services:
  site:
    build:
      context: apache
    volumes:
    - site_statique_data:/var/www
    restart: always
    networks:
    - interne
    - proxy
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      NETWORK_ACCESS: ${NETWORK_ACCESS}
      APACHE_DOCUMENT_ROOT: "/var/www/html"
      TRUSTED_PROXIES: reverse-proxy
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}

  cron:
    build: cron
    volumes:
    - site_statique_data:/site-to-save
    - save_statique_data:/saves
    restart: always
    depends_on:
    - site
    networks:
    - interne

  sftp:
    build: sftp
    restart: always
    volumes:
    - site_statique_data:/home/${USER_SFTP}/site
    - save_statique_data:/home/${USER_SFTP}/save
    networks:
    - sftp
    ports:
    - "22"
    command: ${USER_SFTP}:${PASSWORD_SFTP}:${UID_UTILISATEUR}:${UID_UTILISATEUR}
    environment:
      USER_SFTP: ${USER_SFTP}
      PASS_SFTP: ${PASSWORD_SFTP}

volumes:
  site_statique_data:
    name: site_statique_data
  save_statique_data:
    name: save_statique_data

networks:
  proxy:
    external:
      name: nginx-proxy-wordpress
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
  sftp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'