version: '2'

services:
  db:
    build: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
    - interne

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    depends_on:
    - db
    volumes:
      - wp_data:/var/www/html
      - wp_misc:/var/www/misc
    restart: always
    networks:
    - interne
    - proxy
    - mailing
    - proxyhttp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      NETWORK_ACCESS: ${NETWORK_ACCESS}
      TRUSTED_PROXIES: reverse-proxy
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PASS: ${PROXY_PASS}
      PROXY_USER: ${PROXY_USER}

  cron:
    build: cron
    depends_on:
    - wordpress
    - db
    volumes:
    - wp_data:/site-to-save/html
    - wp_misc:/site-to-save/misc
    - save_data:/saves
    restart: always
    networks:
    - interne
    environment:
      DB_HOST: db
      DB_USER: wordpress
      DB_PASSWORD: wordpress

volumes:
  db_data:
    name: db_data
  wp_data:
    name: wp_data
  wp_misc:
    name: wp_misc
  save_data:
    name: save_data

networks:
  proxy:
    external:
      name: nginx-proxy-wordpress
  mailing:
    external:
      name: postfix-wordpress
  proxyhttp:
    external:
      name: bridge-squid-int
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'