version: '2'

services:
  db:
    build: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_SFTP_SQL}
      MYSQL_USER: ${USER_SFTP_SQL}
      MYSQL_PASSWORD: ${PASSWORD_SFTP_SQL}

  wordpress:
    build: wordpress
    depends_on:
    - db
    volumes:
      - wp_data:/var/www/html
    ports:
    - "990:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USER_SFTP_SQL}
      WORDPRESS_DB_PASSWORD: ${PASSWORD_SFTP_SQL}

volumes:
  db_data:
  wp_data:
