version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    networks:
    - dmz
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    volumes:
    - wp_site_data:/var/www/html
    networks:
    - dmz
    - proxy
    expose:
    - 80
    restart: always
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db_data:
    name: db_data
  wp_site_data:
    name: wp_site_data

networks:
  proxy:
    external:
      name: nginx-proxy-wordpress