version: '2'

services:
  db:
    build: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
    - interne

  wordpress:
    build: wordpress
    depends_on:
    - db
    volumes:
      - wp_data:/var/www/html
    restart: always
    networks:
    - interne
    - proxy
    - mailing
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      NETWORK_ACCESS: ${NETWORK_ACCESS}
      TRUSTED_PROXIES: proxy

volumes:
  db_data:
    name: db_data
  wp_data:
    name: wp_data

networks:
  proxy:
    external:
      name: nginx-proxy-ginfo
  mailing:
    external:
      name: postfix-wordpress
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'