services:
  smbd:
    restart: always
    build: smbd
    tty: true
    volumes:
    - data_samba_config:/etc/samba
    - data_samba_lib:/var/lib/samba
    - data_samba_users:/var/lib/extrausers
    - data_samba_data_public:/data/public
    - data_samba_data_homes:/home
    ports:
    - "135:135"
    - "139:139"
    - "445:445"

volumes:
  data_samba_config:
    name: data_samba_config
  data_samba_lib:
    name: data_samba_lib
  data_samba_users:
    name: data_samba_users
  data_samba_data_homes:
    name: data_samba_data_homes
