version: '2'

services:
  smbd:
    restart: always
    image: rootlogin/samba
    tty: true
    volumes:
    - data/samba_config:/etc/samba
    - data/samba_lib:/var/lib/samba
    - data/users:/var/lib/extrausers
    - data/public:/data/public
    ports:
    - "136:135"
    - "140:139"
    - "446:445"

  netatalk:
    restart: always
    image: rootlogin/netatalk
    volumes:
    - data/netatalk_config:/etc/netatalk
    - data/public:/data/public
    ports:
    - "549:548"

volumes:
  data:
    name: data