# See https://www.loraserver.io/lora-app-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://loraserver_as:loraserver_as@postgresql/loraserver_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"

[application_server.api]
public_host="appserver:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
