version: '2'

services:
  ldap:
    build: ldap
    image: ldap:latest
    volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config: /etc/ldap/slapd.d
    restart: always
    networks:
    - ldap
    environment:
      TRUSTED_PROXIES: reverse-proxy

volumes:
  ldap_data:
    driver: local
    name: ldap_data
  ldap_config:
    driver: local
    name: ldap_config

networks:
  ldap:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
