version: '2'

services:
  ldap:
    build: ldap
    image: ldap:latest
    volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config:/etc/ldap/slapd.d
    restart: always
    networks:
    - ldap
    environment:
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}

volumes:
  ldap_data:
    driver: local
    name: ldap_data
  ldap_config:
    driver: local
    name: ldap_config

networks:
  ldap:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
