services:
  site:
    build: docker-wims
    image: docker-wims:latest
    volumes:
    - wims_data:/home/wims
    restart: always
    networks:
    - interne
    - proxy
    environment:
      VIRTUAL_HOST: ${APP_HOSTNAME}
      NETWORK_ACCESS: ${NETWORK_RESTRICTION}
      APACHE_DOCUMENT_ROOT: ${WEB_ROOT}
      TRUSTED_PROXIES: reverse-proxy

volumes:
  wims_data:
    driver: local


networks:
  proxy:
    name: nginx-proxy-ginfo
    external: true
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
