version: '2'

services:
  nginx-proxy:
    build: proxy
    container_name: reverse-proxy
    ports:
    - "80:80"
    - "443:443"
    restart: always
    networks:
    - proxy_ginfo
    - proxy_wordpress
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  proxy_ginfo:
    external:
      name: nginx-proxy-ginfo
  proxy_wordpress:
    external:
      name: nginx-proxy-wordpress