version: '2'

services:
  nginx-proxy:
    build: proxy
    container_name: reverse-proxy
    ports:
    - "25060:80"
    networks:
    - proxy
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  proxy:
    external:
      name: nginx-proxy