version: '2'

services:
  nginx-proxy:
    container_name: reverse-proxy
    image: jwilder/nginx-proxy
    ports:
    - "25060:80"
    networks:
    - proxy
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  proxy:
    driver: bridge
    name: nginx-proxy
    ipam:
      config:
      - subnet: 172.67.89.0/24
        gateway: 172.67.89.1