version: '2'

services:
  postfix:
    build:
      context: postfix
      args:
        relay: ${RELAY} #SMTP mx.centrale-marseille.fr
        monitoring_email: ${EMAIL_MONITORING} #Où seront envoyés les mails de monitoring du serveur mail
    container_name: postfix
    restart: always
    ports:
    - "25:25"
    networks:
    - internet
    - postfix-ginfo
    - postfix-wordpress

networks:
  internet:
    external:
      name: internet
  postfix-ginfo:
    external:
      name: postfix-ginfo
  postfix-wordpress:
    external:
      name: postfix-wordpress