# See https://www.loraserver.io/loraserver/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://loraserver_ns:loraserver_ns@postgresql/loraserver_ns?sslmode=disable"

[redis]
url="redis://redis:6379"

[network_server]
net_id="000000"

[network_server.band]
# LoRaWAN band to use.
#
# Valid values are:
# *	AS_923
# * AU_915_928
# * CN_470_510
# * CN_779_787
# * EU_433
# * EU_863_870
# * IN_865_867
# * KR_920_923
# * RU_864_870
# * US_902_928
name="EU_863_870"

[network_server.network_settings]
# Enable only a given sub-set of channels
#
# Use this when ony a sub-set of the by default enabled channels are being
# used. For example when only using the first 8 channels of the US band.
# 
# Example:
# enabled_uplink_channels=[0, 1, 2, 3, 4, 5, 6, 7]
enabled_uplink_channels=[]

# Extra channel configuration.
#
# Use this for LoRaWAN regions where it is possible to extend the by default
# available channels with additional channels (e.g. the EU band).
# The first 5 channels will be configured as part of the OTAA join-response
# (using the CFList field).
# The other channels (or channel / data-rate changes) will be (re)configured
# using the NewChannelReq mac-command.
#
# Example:
# [[network_server.network_settings.extra_channels]]
# frequency=867100000
# min_dr=0
# max_dr=5

# [[network_server.network_settings.extra_channels]]
# frequency=867300000
# min_dr=0
# max_dr=5

# [[network_server.network_settings.extra_channels]]
# frequency=867500000
# min_dr=0
# max_dr=5

# [[network_server.network_settings.extra_channels]]
# frequency=867700000
# min_dr=0
# max_dr=5

# [[network_server.network_settings.extra_channels]]
# frequency=867900000
# min_dr=0
# max_dr=5

[network_server.gateway.backend.mqtt]
server="tcp://mosquitto:1883"
username=""
password=""

[join_server.default]
server="http://appserver:8003"

[geolocation_server]
server="geoserver:8005"
