version: '2'

services:
  portainer:
    image: portainer/portainer-ce:2.21.4-alpine
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - "8000:8000"
    - "9000:9000"
    environment:
      VIRTUAL_HOST: docker.ginfo.ec-m.fr
      VIRTUAL_PORT: 9000
      NETWORK_ACCESS: internal
    networks:
    - proxy-ginfo
    - internet

  reverse-proxy:
    build: reverse-proxy
    container_name: reverse-proxy
    restart: always
    networks:
    - proxy-wordpress
    - proxy-ginfo
    environment:
      DEFAULT_HOST: default.asso.centrale-marseille.fr
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - certificates:/etc/nginx/certs
    - /etc/nginx/vhost.d
    - default_nginx_html:/usr/share/nginx/html
    - nginx_basic_auth:/etc/nginx/htpasswd

  letsencrypt-certificator:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: reverse-proxy-letsencrypt-certificator
    environment:
      DEFAULT_EMAIL: ginfo@centrale-marseille.fr
    networks:
    - proxy-ginfo
    - proxy-wordpress
    - internet
    restart: always
    volumes_from:
      - reverse-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer_data:
    external: true
  certificates:
    external: true
  default_nginx_html:
    external: true
  nginx_basic_auth:
    external: true
  acme:

networks:
  proxy-ginfo:
    external: true
    name: nginx-proxy-ginfo
  proxy-wordpress:
    external: true
    name: nginx-proxy-wordpress
  internet:
    external: true
    name: internet
