services:
  squid:
    build:
     context: squid
     args:
       gateway: ${GATEWAY}
    ports:
      - "3128:3128"
    container_name: squid
    cap_add:
    - NET_ADMIN
    networks:
      - bridge-squid-int
      - bridge-squid-wordpress
      - internet
    volumes:
    - cache:/var/spool/squid
    - config:/etc/squid/
    restart: always

volumes:
  cache:
  config:

networks:
  bridge-squid-int:
    name: bridge-squid-int
    external: true
  bridge-squid-wordpress:
    name: bridge-squid-wordpress
    external: true
  internet:
    name: internet
    external: true
