version: '2'

services:
  postfix:
    build:
      context: unbound
    container_name: dns
    restart: always
    ports:
    - "53:53"
    networks:
    - bridge

networks:
  bridge:
    external:
      name: bridge