version: '2'

services:
  pptp:
    build:
      context: ./pptp
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        PASSWORD: ${PASSWORD}
    ports:
    - "1723:1723"
    networks:
    - internet
    restart: always
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}

volumes:
  pptp:
    name: pptp

networks:
  internet:
    external:
      name: internet