version: '2'

services:
  pptp:
    build:
      context: ./pptp
      dockerfile: Dockerfile
      args:
        username: ${USERNAME}
        password: ${PASSWORD}
    ports:
    - "1727:1723"
    volumes:
    - pptp:/etc/ppp
    restart: always
    privileged: true
    network_mode: host

volumes:
  pptp:
    name: pptp