version: '2'

services:
  pptp:
    build: pptp
    ports:
    - "1727:1723"
    volumes:
    - pptp:/etc/ppp
    restart: always
    privileged: true
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    network_mode: host

volumes:
  pptp:
    name: pptp