version: "2"

services:
  loraserver:
    build: loraserver
    volumes:
      - loraserver:/etc/loraserver

  appserver:
    build: lora-app-server
    ports:
      - 8080:8080
    volumes:
      - lora-app-server:/etc/lora-app-server
  
  geoserver:
    build: lora-geo-server
    volumes:
      - lora-geo-server:/etc/lora-geo-server
  
  postgresql:
    build: postgresql
    volumes:
      - initdbconf:/docker-entrypoint-initdb.d
      - data-postgresql:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - data-redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
