services:
  loraserver:
    build: loraserver
    volumes:
      - loraserver:/etc/loraserver
    networks:
      - interne
    restart: always

  appserver:
    build: lora-app-server
    environment:
      VIRTUAL_HOST: ${APP_HOSTNAME}
      NETWORK_ACCESS: ${NETWORK_RESTRICTION}
    expose:
    - "8080"
    volumes:
      - lora-app-server:/etc/lora-app-server
    networks:
      - interne
      - proxy
    restart: always

  geoserver:
    build: lora-geo-server
    volumes:
      - lora-geo-server:/etc/lora-geo-server
    networks:
      - interne
    restart: always

  postgresql:
    build: postgresql
    volumes:
      - lora-initdbconf:/docker-entrypoint-initdb.d
      - lora-data-postgresql:/var/lib/postgresql/data
    networks:
      - interne
    restart: always

  redis:
    image: redis:4-alpine
    volumes:
      - lora-data-redis:/data
    networks:
      - interne
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - lora-mqtt-config:/mosquitto/config
      - lora-mqtt-data:/mosquitto/data
      - lora-mqtt-log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      - interne
    restart: always

volumes:
  loraserver:
    name: loraserver
  lora-app-server:
    name: lora-app-server
  lora-geo-server:
    name: lora-geo-server
  lora-initdbconf:
    name: lora-initdbconf
  lora-data-postgresql:
    name: lora-data-postgresql
  lora-data-redis:
    name: lora-data-redis
  lora-mqtt-config:
    name: lora-mqtt-config
  lora-mqtt-data:
    name: lora-mqtt-data
  lora-mqtt-log:
    name: lora-mqtt-log

networks:
  proxy:
    name: nginx-proxy-ginfo
    external: true
  interne:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
